@startuml

|**Source code develop repository**|
start
:Code wijziging;
|//Build pipeline//|
:Build App;
:Unit tests backend/frontend;
:Static code analysis;
if (Succes) then (nee)
    end
else (ja)
    :Publiceer product;
endif

|**Build repository**|
:App Release kandidaat (RC)/
|//Integratie pipeline//|
:Deploy RC naar testomgeving;
:Uitvoeren integratie tests;
if (Succes) then (nee)
    end
else (ja)
    :Promoveer product;
endif
|**Release repository**|
:Released App/
|**Klant omgeving(en)**|
-[dashed]->
:Installeer release;
detach
@enduml