@startuml 
title Qwik context diagram\n(productie)

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml
'Layout actors 
skinparam actor {
    StereotypeFontColor #444444
    FontColor #444444
    BackgroundColor #F0F0FE
    BorderColor PERSON_BG_COLOR
}
!define User(e_alias, e_label, e_descr) actor "==e_label\n\n e_descr" <<person>> as e_alias
'/Layout actors

Enterprise_Boundary(IGH,"Feniqs") {
    User(inrichter,"Qwik inrichters", "Werknemer van Feniqs")
    System(Browser, "Webbrowser","Chrome | Safari |\nIE 11 | MS Edge")
}

System_Ext(afnemer,"Externe afnemers", "Afnemer van pensioen informatie")

Enterprise_Boundary(Klant,"Pensioenfonds/verzekeraar Intranet") {
    User(eindgebruiker,"Qwik eindgebruiker", "Beheerder van pensioenfondsen/verzekeringen")

    System_Boundary(KlantWerkplek,"Eindgebruiker werkplek") {
        System(QwikFX, "Qwik Eindgebruiker App", "JavaFX")
    }
    System_Boundary(Bastion,"Inrichter werkplek") {
        System(QwikAdmin, "Qwik Inrichter App\n(huidig)", "JavaFX")
    }
    System_Boundary(Qwik,"Server") {
        System(QwikServer, "Qwik Server", "Java")
        System(QwikDatabase,"Qwik Database", "Microsoft SQL | Oracle")
        System(QwikWebGUI,"Qwik Web App\n(toekomst)", "JHipster\n[SpringBoot, React /w Typescript]")
        QwikServer -up-> QwikDatabase
        QwikFX --> QwikDatabase
        QwikWebGUI --> QwikDatabase: [jdbc]
        QwikAdmin -left-> QwikDatabase
    }
    System(DNS,"Domain Name System Server")
    
    QwikServer -[hidden]left- DNS
    Browser -[hidden]- QwikAdmin
}

inrichter -left-> Browser: Inrichten van Qwik\n//(toekomstige situatie)//
Browser -left-> QwikWebGUI: [https] (over VPN)
inrichter .left.> QwikAdmin: Inrichten van Qwik\n[fysiek op lokatie]\n//(huidige situatie)//
eindgebruiker --> QwikFX: Administreren van pensioenen in Qwik
afnemer -up-> QwikServer: Uitvragen van overzichten\n[SOAP over https]
@enduml