@startuml 
title Qwik context diagram\n(productie)

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml
!include c4/c4-user.puml

Enterprise_Boundary(IGH,"Feniqs") {
    User(inrichter,"Qwik inrichters", "Werknemer van Feniqs")
}

System_Ext(afnemer,"Externe afnemers", "Afnemer van pensioen informatie")

Enterprise_Boundary(Klant,"Pensioenfonds/verzekeraar Intranet") {
    User(eindgebruiker,"Qwik eindgebruiker", "Beheerder van pensioenfondsen/verzekeringen")

    System_Boundary(KlantWerkplek,"Eindgebruiker werkplek") {
        System(QwikFX, "Qwik Eindgebruiker App", "JavaFX")
    }
    System_Boundary(Bastion,"Inrichter werkplek\n(Bastion host/VPN Server)") {
        System(Browser, "Webbrowser","Chrome | Safari |\nIE 11 | MS Edge")
        System(QwikAdmin, "Qwik Inrichting App\n(huidig)", "JavaFX")
    }
    System_Boundary(Qwik,"Server") {
        System(QwikServer, "Qwik Server", "Java")
        System(QwikDatabase,"Qwik Database", "Microsoft SQL")
        System(QwikWebGUI,"Qwik Web App\n(toekomst)", "JHipster\n[SpringBoot, React /w Typescript]")
        QwikServer -up-> QwikDatabase
        QwikFX --> QwikDatabase
        QwikWebGUI --> QwikDatabase: [jdbc]
        QwikAdmin --> QwikDatabase
    }
    System(DNS,"Domain Name System Server")
    
    QwikServer -[hidden]left- DNS
    Browser -[hidden]- QwikAdmin
}

inrichter -left-> Browser: Inrichten van Qwik\n[VPN]\n//(toekomstige situatie)//
Browser -left-> QwikWebGUI: [https]
inrichter .left.> QwikAdmin: Inrichten van Qwik\n[VPN of fysiek op lokatie]\n//(huidige situatie)//
eindgebruiker --> QwikFX: Administreren van pensioenen in Qwik
afnemer -up-> QwikServer: Uitvragen van overzichten\n[SOAP over https]
@enduml