==== Ascii Doctor

De documentatie van dit product is gegenereerd met Ascii Doctor.
Ascii Doctor is een doc-as-code oplossing waarbij de documentatie bij de code wordt bewaard en geversioneerd.
Tijdens het maken van het software product wordt deze documentatie omgezet naar PDF (of HTML5) en kan eventueel worden uitgeleverd met het product.

Quick reference: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

==== Diagrammen

De diagrammen in deze documentatie zijn opgesteld in PlantUML.
Tijdens het maken van het software product worden de diagrammen m.b.v. Graphviz omgezet naar een afbeelding en in de documentatie opgenomen.

Download Graphviz (voor Windows): https://graphviz.org/_pages/Download/Download_windows.html.

Installeer Graphviz naar C:\Program Files (x86)\Graphviz2.38\ en dan zou dit project de diagrammen automatisch moeten omzetten tijdens het bouwen.

TIP: In de pom.xml van het project is opgenomen waar Graphviz lokaal is geinstalleerd.

PlantUML Quick Reference: https://plantuml.com/

Preview in Microsoft Visual Studio Code is mogelijk door de plantuml plugin te installeren.

Voorbeeld van een class diagram:
[plantuml, class-diagram-example, png]     
....
include::diagram-examples/class-diagram-example.puml[]
....

Voorbeeld van een C4 diagram:

[plantuml, systeem-context-diagram-example, png]     
....
include::diagram-examples/banking-systeem-context.puml[]
....
