skinparam actor {
    StereotypeFontColor #444444
    FontColor #444444
    BackgroundColor #E0E0EE
    BorderColor PERSON_BG_COLOR
}

!define User(e_alias, e_label) actor "==e_label" <<person>> as e_alias
!define User(e_alias, e_label, e_descr) actor "==e_label\n\n e_descr" <<person>> as e_alias

!define User_Ext(e_alias, e_label) actor "==e_label" <<external_person>> as e_alias
!define User_Ext(e_alias, e_label, e_descr) actor "==e_label\n\n e_descr" <<external_person>> as e_alias
